name: replication-work-hours-covid
channels:
  - opensourceeconomics
  - conda-forge
  - defaults
  - r
  - pytask
dependencies:
  - pytask
  - pytask-parallel
  - conda-build
  - fastparquet=0.4
  - ipykernel
  - jupyterlab
  - pandas=1.3.5
  - matplotlib>=3.4.1
  - pip
  - pyarrow=1.0
  - python=3.7
  - scikit-learn
  - scipy=1.5
  - seaborn=0.11
  - sphinx=3.2
  - statsmodels=0.11
  - utilities
  - tabulate
  - sphinx
  - sphinxcontrib-bibtex
  - xlrd
  - html5lib
  - lxml
  - openpyxl
  - nodejs
  - nb_black
  - r-arrow=1.0
  - r-askpass=1.1
  - r-assertthat=0.2
  - r-backports=1.1
  - r-base=4.0
  - r-base64enc=0.1_3
  - r-bit=4.0
  - r-bit64=4.0
  - r-blob=1.2
  - r-boot=1.3_25
  - r-broom=0.7
  - r-broom.mixed=0.2
  - r-callr=3.4
  - r-cellranger=1.1
  - r-checkmate=2.0
  - r-cli=2.0
  - r-clipr=0.7
  - r-coda=0.19_3
  - r-colorspace=1.4_1
  - r-commonmark=1.7
  - r-crayon=1.3
  - r-cubelyr=1.0
  - r-curl=4.3
  - r-data.table
  - r-dbi=1.1
  - r-dbplyr=1.4
  - r-deriv=4.0
  - r-desc=1.2
  - r-digest=0.6
  - r-doby=4.6
  - r-dplyr=1.0
  - r-ellipsis=0.3
  - r-evaluate=0.14
  - r-fansi=0.4
  - r-farver=2.0
  - r-forcats=0.5
  - r-formula=1.2_3
  - r-fs=1.5
  - r-generics=0.0.2
  - r-ggplot2=3.3
  - r-gh=1.1
  - r-git2r=0.27
  - r-glue=1.4
  - r-gt=0.2
  - r-gtable=0.3
  - r-gtsummary=1.3
  - r-haven=2.3
  - r-highr=0.8
  - r-hms=0.5
  - r-htmltools=0.5
  - r-httr=1.4
  - r-huxtable=5.1
  - r-ini=0.3
  - r-isoband=0.2
  - r-iterators=1.0
  - r-jsonlite=1.7
  - r-knitr=1.29
  - r-labeling=0.3
  - r-lattice=0.20_41
  - r-lfe=2.8_5.1
  - r-lifecycle=1.0
  - r-lme4=1.1_23
  - r-lubridate=1.7
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-memoise=1.1
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-minqa=1.2
  - r-modelr=0.1
  - r-munsell=0.5
  - r-nlme=3.1_149
  - r-nloptr=1.2
  - r-openssl=1.4
  - r-pbkrtest=0.4_8
  - r-pillar=1.4
  - r-pkgbuild=1.1
  - r-pkgconfig=2.0
  - r-pkgload=1.1
  - r-plyr=1.8
  - r-praise=1.0
  - r-prettyunits=1.1
  - r-processx=3.4
  - r-progress=1.2
  - r-ps=1.3
  - r-purrr=0.3
  - r-quantreg
  - r-r6=2.4
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0
  - r-rcppeigen=0.3
  - r-readr=1.3
  - r-readxl=1.3
  - r-rematch=1.0
  - r-rematch2=2.1
  - r-reprex=0.3
  - r-reshape2=1.4
  - r-rjson=0.2
  - r-rlang=0.4
  - r-rmarkdown=2.3
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.11
  - r-rvest=0.3
  - r-sandwich=2.5_1
  - r-sass=0.2
  - r-scales=1.1
  - r-selectr=0.4_2
  - r-sfsmisc=1.1_7
  - r-stargazer=5.2
  - r-statmod=1.4
  - r-stringi=1.5
  - r-stringr=1.4
  - r-survival=3.2_3
  - r-sys=3.4
  - r-testthat=2.3
  - r-tibble=3.0
  - r-tidyr=1.1
  - r-tidyselect=1.1
  - r-tidyverse=1.3
  - r-tinytex=0.25
  - r-tmb=1.7
  - r-usethis=1.6
  - r-utf8=1.1
  - r-vctrs=0.3
  - r-viridislite=0.3
  - r-whisker=0.4
  - r-withr=2.2
  - r-xfun=0.17
  - r-xml2=1.3
  - r-xtable=1.8_4
  - r-yaml=2.2
  - r-zeallot=0.1
  - r-zoo=1.8_8
  - pip:
    - savReaderWriter
    - pyreadstat